name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: "_deps"
          key: deps-${{ runner.os }}

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libharfbuzz-dev libfreetype-dev libasound2-dev
          version: 1.0

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.6
          actions-cache-folder: "emsdk-cache"

      - name: Run CMake
        run: emcmake cmake -G "Unix Makefiles" .

      - name: Make
        run: emmake make -j4
